package com.ankita.projecteuler;
/**
* Problem 2: Even Fibonacci Numbers
* Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
* By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
* @author patil
*
*/
public class EvenFibonacciNumber {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		
		int number1 = 1;
		int number2 = 2;
		int sum = 0;
		
		while (number1 < 4000000) {
			if (number1 % 2 == 0){
				sum += number1;
			}
			
			number2 = number1 + number2; 
			number1 = number2 - number1; 
		}
		System.out.println(sum);

	}

}
